### PR TITLE
Added support for dynamic argument resolution in tag

### PR DESCRIPTION
**Pull request by joshhills**
Hi,

I thought instead of raising an issue I'd make this quite simple change myself. I'd love to see this feature in the main repository so I can point my gem include back to it.

## Problem
I'm building a theme where each post may have a front-matter variable naming a Jupyter Notebook file to display. The tag is included in the post template, positioned separately from the content of the post, and therefore the notebook's path cannot be hard-coded. Attempting to pass a variable into the tag in its current state does not work, e.g.

```
_posts
  2018-06-06-my-post.md <-- Has front matter variable "notebook_path" set to "test.ipynb"
_layouts
  post.html <-- Uses custom jupyter tag
```

```
{% assign notebook_path = "/assets/notebooks/" | append: page.notebook_path %}
<!-- By this point notebook_path resolves to "/assets/notebooks/test.ipynb" -->
{% jupyter_notebook notebook_path %}
<!-- Uh-oh! This attempts to render '/notebook_path.html' in the iframe -->
```

## Solution
Googling around, it seems a short, clean and extensible solution to parsing tag parameters is to scan the markup argument for tag attributes and switch on relevant ones. I set a flag if it appears the user is attempting to denote the path as a variable, e.g.

`{% jupyter_notebook notebook_path: my_variable %}`

If this flag is set when render is called, it uses the page context to resolve the variable name to its value, replacing the notebook_path string literal text with something dynamic. Otherwise, it falls back to said string.

## Notes
The change is backward compatible - it only triggers if there is a colon following the parameter name e.g.

```
{% jupyter_notebook notebook_path %}
<!-- This still attempts to render '/notebook_path.html' in the iframe -->
```

I've also incremented the build number and updated your documentation method. Because I'm unsure of your build chain, and there was no contribution guide, feel free to let me know if there are steps I have missed in order to conform with your repository's standards.

### CODE REVIEW

**Comment by kou** [comment]
Can you provide a sample Jekyll site to test this case?

**Comment by joshhills** [comment]
I've extended the blog post in the example site you've already provided to showcase this alternative functionality.

image

Accessible at http://localhost:4000/2017/09/03/blog when serving.

**Comment by kou** [comment]
Thanks. I could confirm.

I've removed `notebook_path: ...` syntax. I've added more powerful variable reference support instead. Now we can use filter:

```text
{::nomarkdown}
{% assign notebook_path = "/notebooks/blog" %}
{% jupyter_notebook notebook_path | append: ".ipynb"%}
{:/nomarkdown}
```

I've changed to require string literal (quotation is required):

```text
{::nomarkdown}
{% jupyter_notebook "/notebooks/blog.ipynb" %}
{:/nomarkdown}
```

But no quoted path is still supported for backward compatibility:

```text
{::nomarkdown}
{% jupyter_notebook /notebooks/blog.ipynb %}
{:/nomarkdown}
```

**Comment by joshhills** [comment]
Looks great, thankyou.

**Pull request merged**
